AWSTemplateFormatVersion: '2010-09-09'
Resources:
  GlueDatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseInput:
        Name: transformed_data

  ProductsTable:
    Type: 'AWS::Glue::Table'
    Properties:
      DatabaseName: !Ref GlueDatabase
      CatalogId: !Ref "AWS::AccountId"
      TableInput:
        Name: products
        StorageDescriptor:
          Columns:
            - Name: product_id
              Type: int
            - Name: product_name
              Type: string
            - Name: aisle_id
              Type: int
            - Name: department_id
              Type: int
          Location: "s3://data14group1-transformed/products/"
          InputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"

  DepartmentsTable:
    Type: 'AWS::Glue::Table'
    Properties:
      DatabaseName: !Ref GlueDatabase
      CatalogId: !Ref "AWS::AccountId"
      TableInput:
        Name: departments
        StorageDescriptor:
          Columns:
            - Name: department_id
              Type: int
            - Name: department
              Type: string
          Location: "s3://data14group1-transformed/departments/"
          InputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"

  AislesTable:
    Type: 'AWS::Glue::Table'
    Properties:
      DatabaseName: !Ref GlueDatabase
      CatalogId: !Ref "AWS::AccountId"
      TableInput:
        Name: aisles
        StorageDescriptor:
          Columns:
            - Name: aisle_id
              Type: int
            - Name: aisle
              Type: string
          Location: "s3://data14group1-transformed/aisles/"
          InputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"

  ProductsDenormTable:
    Type: 'AWS::Glue::Table'
    Properties:
      DatabaseName: !Ref GlueDatabase
      CatalogId: !Ref "AWS::AccountId"
      TableInput:
        Name: products_denorm
        StorageDescriptor:
          Columns:
            - Name: product_id
              Type: int
            - Name: product_name
              Type: string
            - Name: aisle_id
              Type: int
            - Name: aisle
              Type: string
            - Name: department_id
              Type: int
            - Name: department
              Type: string
          Location: "s3://data14group1-transformed/products_denorm/"
          InputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"
