AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  scriptsBucket:
    Type: String
  rawBucket:
    Type: String
  stagingBucket:
    Type: String
  transformedBucket:
    Type: String
  mlBucket:
    Type: String
  lambdaRaw2stagingVersion:
    Type: String
  rootEmail:
    Type: String

Resources:
  GlueJobStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/glueJob.yml"
      Parameters:
        scriptsBucket: !Ref scriptsBucket

  LambdaStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/lambda.yml"
      Parameters:
        scriptsBucket: !Ref scriptsBucket
        rawBucket: !Ref rawBucket
        stagingBucket: !Ref stagingBucket
        lambdaRaw2stagingVersion: !Ref lambdaRaw2stagingVersion

  GlueCatalogStagingStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/glueCatalogStaging.yml"
      Parameters:
        stagingBucket: !Ref stagingBucket

  GlueCatalogTransformedStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/glueCatalogTransformed.yml"
      Parameters:
        transformedBucket: !Ref transformedBucket

  GlueCatalogMLStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/glueCatalogML.yml"
      Parameters:
        mlBucket: !Ref mlBucket



  # SNS Topic
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: GlueJobFailureNotifications

  # SNS Topic Subscription
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopic
      Protocol: email
      Endpoint: !Ref rootEmail

  StepFunctionStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/stepFunction.yml"
      Parameters:
        LambdaFunctionArn:
          ImportValue: !Sub "${LambdaStack}-CopyFilesLambdaArn"

  # EventBridge Rule
  EventBridgeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${scriptsBucket}/cloudformation/eventBridge.yml
      TimeoutInMinutes: 10
      Parameters:
        StateMachineArn:
          ImportValue: !Sub "${StepFunctionStack}-StateMachineArn"


