AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  scriptsBucket:
    Type: String
  rawBucket:
    Type: String
  stagingBucket:
    Type: String
  transformedBucket:
    Type: String
  mlBucket:
    Type: String
  lambdaRaw2stagingVersion:
    Type: String

Resources:
  GlueJobStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/glueJob.yml"
      Parameters:
        scriptsBucket: !Ref scriptsBucket

  LambdaStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/lambda.yml"
      Parameters:
        scriptsBucket: !Ref scriptsBucket
        rawBucket: !Ref rawBucket
        stagingBucket: !Ref stagingBucket
        lambdaRaw2stagingVersion: !Ref lambdaRaw2stagingVersion

  GlueCatalogStagingStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/glueCatalogStaging.yml"
      Parameters:
        stagingBucket: !Ref stagingBucket

  GlueCatalogTransformedStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/glueCatalogTransformed.yml"
      Parameters:
        transformedBucket: !Ref transformedBucket

  GlueCatalogMLStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/glueCatalogML.yml"
      Parameters:
        mlBucket: !Ref mlBucket

#  StepFunctionStack:
#    Type: 'AWS::CloudFormation::Stack'
#    Properties:
#      TemplateURL: !Sub "https://s3.amazonaws.com/${scriptsBucket}/cloudformation/stepFunction.yml"
#      Parameters:
#        scriptsBucket: !Ref scriptsBucket


