AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LambdaRaw2StagingArn:
    Type: String
    Description: ARN of the Lambda function
  GlueJobCsv2ParquetArn:
    Type: String
    Description: ARN of the Gluejob csv2parquet
  GlueJobETLArn:
    Type: String
    Description: ARN of the Gluejob ETL
  scriptsBucket:
    Type: String
    Description: S3 bucket name where scripts will be uploaded

Resources:

  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StepFunctionsExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionsExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - sns:Publish
                Resource: '*'

  PipelineStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: PipelineStateMachine
      RoleArn: !GetAtt StepFunctionsExecutionRole.Arn
      DefinitionString: !Sub |
        {
          "Comment": "datalake pipeline for data14 group1 project",
          "StartAt": "RunGlueJobETL",
          "States": {
            "RunGlueJobETL": {
              "Type": "Task",
              "Resource": "${GlueJobETLArn}",
              "Parameters": {
                "JobName": "GlueJobETL"
              },
              "Next": "Success"
            },
            "Success": {
              "Type": "Succeed"
            }
          }
        }
        
        
        

#        {
#          "Comment": "datalake pipeline for data14 group1 project",
#          "StartAt": "RunLambda",
#          "States": {
#            "RunLambda": {
#              "Type": "Task",
#              "Resource": "${LambdaRaw2StagingArn}",
#              "Next": "CheckLambdaResult",
#              "Catch": [
#                {
#                  "ErrorEquals": ["States.ALL"],
#                  "Next": "NotifyFailure"
#                }
#              ]
#            },
#            "CheckLambdaResult": {
#              "Type": "Choice",
#              "Choices": [
#                {
#                  "Variable": "$.raw2staging.statusCode",
#                  "NumericEquals": 200,
#                  "Next": "RunGlueJobCsv2Parquet"
#                }
#              ],
#              "Default": "NotifyFailure"
#            },
#            "RunGlueJobCsv2Parquet": {
#              "Type": "Task",
#              "Resource": "${GlueJobCsv2ParquetArn}",
#              "Parameters": {
#                "JobName": "GlueJobCsv2Parquet"
#              },
#              "Next": "CheckGlueJobCsv2ParquetResult",
#              "Catch": [
#                {
#                  "ErrorEquals": ["States.ALL"],
#                  "Next": "NotifyFailure"
#                }
#              ]
#            },
#            "CheckGlueJobCsv2ParquetResult": {
#              "Type": "Choice",
#              "Choices": [
#                {
#                  "Variable": "$.GlueJobCsv2Parquet.Status",
#                  "StringEquals": "SUCCEEDED",
#                  "Next": "RunGlueJobETL"
#                }
#              ],
#              "Default": "NotifyFailure"
#            },
#            "RunGlueJobETL": {
#              "Type": "Task",
#              "Resource": "${GlueJobETLArn}",
#              "Parameters": {
#                "JobName": "GlueJobETL"
#              },
#              "Next": "CheckGlueJobETLResult",
#              "Catch": [
#                {
#                  "ErrorEquals": ["States.ALL"],
#                  "Next": "NotifyFailure"
#                }
#              ]
#            },
#            "CheckGlueJobETLResult": {
#              "Type": "Choice",
#              "Choices": [
#                {
#                  "Variable": "$.GlueJobETL.Status",
#                  "StringEquals": "SUCCEEDED",
#                  "Next": "Success"
#                }
#              ],
#              "Default": "NotifyFailure"
#            },
#            "Success": {
#              "Type": "Succeed"
#            },
#            "NotifyFailure": {
#              "Type": "Task",
#              "Resource": "arn:aws:states:::sns:publish",
#              "Parameters": {
#                "TopicArn": "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:GlueJobFailureNotifications",
#                "Message": {
#                  "Error": "An error occurred in the Step Function",
#                  "Details.$": "$"
#                },
#                "Subject": "Data14 Group1 Data Pipeline Error Notification"
#              },
#              "End": true
#            }
#          }
#        }




Outputs:
  StateMachineArn:
    Description: "Step Function ARN"
    Value: !GetAtt PipelineStateMachine.Arn
