AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  scriptsBucket:
    Type: String
    Description: S3 bucket name where scripts will be uploaded
    
Resources:
  StepFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: StepFunctionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSStepFunctionsFullAccess
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AWSGlueServiceRole

  StateMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      StateMachineName: DataLakePipeline
      RoleArn: !GetAtt StepFunctionRole.Arn
      DefinitionS3Location:
        Bucket: !Ref scriptsBucket
        Key: statemachines/dataLakePipeline.json

  EventBridgeRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: DailyTrigger
      ScheduleExpression: 'rate(1 day)'
      State: 'ENABLED'
      Targets:
        - Arn: !GetAtt StateMachine.Arn
          Id: StateMachineTarget
