AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CopyFilesLambdaArn:
    Type: String
    Description: ARN of the Lambda function
  scriptsBucket:
    Type: String
    Description: S3 bucket name where scripts will be uploaded

Resources:
  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt StepFunctionsExecutionRole.Arn
      DefinitionS3Location:
        Bucket: !Ref scriptsBucket
        Key: statemachines/dataLakePipeline.json
      DefinitionSubstitutions:
        CopyFilesLambdaArn: !Ref CopyFilesLambdaArn

  # Step Functions Execution Role
  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionsExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - sns:Publish
                Resource: '*'
Outputs:
  StateMachineArn:
    Description: "Step Function ARN"
    Value: !GetAtt MyStateMachine.Arn
    Export:
      Name: !Sub "${AWS::StackName}-StateMachineArn"
