name: Deploy CloudFormation Stacks

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region"
        required: true
        default: "ap-southeast-2"
      bucketName:
        description: "S3 Bucket Name"
        default: "data14-group-one"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cfn-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SAM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SAM_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Upload Spark code to S3
        run: aws s3 cp ETL/Sam/ETL-job.py s3://${{ github.event.inputs.bucketName }}/glueJobCodes/ETL-job.py

      - name: Deploy CloudFormation Stacks
        id: deploy-cloudformation
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name:  deploy-cloudformation
          template: cfn/lakeformation.yml
          parameter-overrides: BucketName=${{ github.event.inputs.bucketName }}
